#!/usr/bin/env bash
# Suprema Node — bridge installer.
#
# Usage:  curl -fsSL https://supremanode.com/install.sh | bash
#    or:  curl -fsSL https://raw.githubusercontent.com/supremanode/bridge/main/install.sh | bash
#    or:  ./install.sh [--relay URL] [--branch main]
#
# What this does:
#   1. checks node + pnpm (or installs pnpm)
#   2. clones the public bridge repo (or updates if present)
#   3. installs deps + builds (compiles TypeScript)
#   4. prompts for the relay URL (or uses --relay)
#   5. writes .env
#   6. installs a systemd user service (Linux) or prints the run command
#
# The bridge polls the relay for tasks and runs them via a detected harness
# (claude-code, codex, pi, etc.). It needs node; it does NOT need the relay's
# Postgres or any DB.
set -euo pipefail

BRIDGE_DIR="${BRIDGE_DIR:-$HOME/.suprema/bridge}"
REPO="${REPO:-https://github.com/supremanode/bridge.git}"
BRANCH="${BRANCH:-main}"
RELAY_URL=""
PAIR_TOKEN="" # v3.31: base64url({r:relay,k:key}) from Settings QR — skips all prompts

# ── arg parse ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --relay)   RELAY_URL="$2"; shift 2 ;;
    --pair)    PAIR_TOKEN="$2"; shift 2 ;;
    --branch)  BRANCH="$2"; shift 2 ;;
    --dir)     BRIDGE_DIR="$2"; shift 2 ;;
    -h|--help) echo "Usage: install.sh [--relay URL] [--pair TOKEN] [--branch main] [--dir PATH]"; exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Decode the pair token early so the relay prompt is skipped entirely.
if [[ -n "$PAIR_TOKEN" ]]; then
  PAIR_JSON="$(printf '%s' "$PAIR_TOKEN" | tr '_-' '/+' | base64 -d 2>/dev/null || true)"
  RELAY_URL="$(printf '%s' "$PAIR_JSON" | sed -n 's/.*"r":"\([^"]*\)".*/\1/p')"
  PAIR_KEY="$(printf '%s' "$PAIR_JSON" | sed -n 's/.*"k":"\([^"]*\)".*/\1/p')"
  if [[ -z "$RELAY_URL" || -z "$PAIR_KEY" ]]; then
    echo "✗ invalid --pair token (no relay/key inside)"
    exit 1
  fi
  echo "✓ pair token decoded — relay: $RELAY_URL"
fi

echo "╔════════════════════════════════════════════╗"
echo "║   Suprema Node — bridge installer          ║"
echo "╚════════════════════════════════════════════╝"
echo "  target: $BRIDGE_DIR"
echo "  repo:   $REPO ($BRANCH)"
echo ""

# ── 1. prerequisites ───────────────────────────────────────────────────────
if ! command -v node >/dev/null 2>&1; then
  echo "✗ node not found. Install Node 20+: https://nodejs.org"
  exit 1
fi
echo "✓ node $(node --version)"

if ! command -v pnpm >/dev/null 2>&1; then
  echo "  installing pnpm…"
  npm install -g pnpm >/dev/null 2>&1 || corepack enable pnpm >/dev/null 2>&1 || true
fi
command -v pnpm >/dev/null 2>&1 && echo "✓ pnpm $(pnpm --version)" || { echo "✗ pnpm install failed"; exit 1; }

if ! command -v git >/dev/null 2>&1; then
  echo "✗ git not found. Install git: https://git-scm.com"
  exit 1
fi

# ── 2. clone or update ─────────────────────────────────────────────────────
if [[ -d "$BRIDGE_DIR/.git" ]]; then
  echo "  updating existing clone…"
  git -C "$BRIDGE_DIR" fetch --quiet origin
  git -C "$BRIDGE_DIR" checkout "$BRANCH" --quiet
  git -C "$BRIDGE_DIR" reset --hard "origin/$BRANCH" --quiet
else
  echo "  cloning bridge repo…"
  mkdir -p "$(dirname "$BRIDGE_DIR")"
  git clone --depth 1 --branch "$BRANCH" "$REPO" "$BRIDGE_DIR" --quiet
fi
echo "✓ code at $BRIDGE_DIR"

# ── 3. install deps + build ────────────────────────────────────────────────
echo "  installing dependencies (this takes a minute)…"
( cd "$BRIDGE_DIR" && pnpm install --frozen-lockfile >/dev/null 2>&1 || pnpm install >/dev/null 2>&1 )
echo "✓ dependencies installed"

echo "  building (compiling TypeScript)…"
( cd "$BRIDGE_DIR" && pnpm build >/dev/null 2>&1 )
echo "✓ build complete"

# ── 4. relay URL ───────────────────────────────────────────────────────────
# --pair mode: RELAY_URL already set from the token — no prompt.
if [[ -z "$RELAY_URL" ]]; then
  # default: this machine's Tailscale IP if present
  TS_IP="$(tailscale ip -4 2>/dev/null || true)"
  DEFAULT_RELAY="${TS_IP:+http://$TS_IP:4000}"
  if [[ -n "${DEFAULT_RELAY:-}" ]]; then
    read -r -p "Relay URL [$DEFAULT_RELAY]: " RELAY_URL
    RELAY_URL="${RELAY_URL:-$DEFAULT_RELAY}"
  else
    read -r -p "Relay URL (e.g. https://relay.supremanode.com): " RELAY_URL
  fi
  if [[ -z "$RELAY_URL" ]]; then
    echo "✗ relay URL required"
    exit 1
  fi
fi

# ── 5. write .env ──────────────────────────────────────────────────────────
BRIDGE_ID="$(hostname)-$(date +%s | tail -c 5)"
cat > "$BRIDGE_DIR/.env" <<EOF
# Suprema Node bridge — generated by install.sh${PAIR_TOKEN:+ (paired)}
BRIDGE_ID=$BRIDGE_ID
RELAY_URL=$RELAY_URL${PAIR_KEY:+
BRIDGE_KEY=$PAIR_KEY}
# poll interval (ms)
BRIDGE_POLL_MS=2000
EOF
echo "✓ configured for relay: $RELAY_URL (id: $BRIDGE_ID)${PAIR_KEY:+ · key paired}"

# ── 6. start (systemd if Linux, else print cmd) ────────────────────────────
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "  Install complete."
echo ""
echo "  Run once to test:"
echo "    cd $BRIDGE_DIR && pnpm start"
echo ""
echo "  Add a harness so it can execute tasks:"
echo "    npm i -g @anthropic-ai/claude-code   # or: codex, pi, aider"
echo ""

if [[ "$(uname -s)" == "Linux" ]] && command -v systemctl >/dev/null 2>&1; then
  # Inline systemd user service (no external service.sh dependency).
  UNIT_DIR="$HOME/.config/systemd/user"
  mkdir -p "$UNIT_DIR"
  cat > "$UNIT_DIR/suprema-bridge.service" <<UNIT
[Unit]
Description=Suprema Node bridge — connects relay to local coding agents
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$BRIDGE_DIR
EnvironmentFile=$BRIDGE_DIR/.env
ExecStart=$(command -v node) $BRIDGE_DIR/dist/index.js
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload
  systemctl --user enable suprema-bridge.service 2>/dev/null || true
  echo "  Run as a background service (Linux):"
  echo "    systemctl --user start suprema-bridge"
  echo "    systemctl --user status suprema-bridge   # check logs"
  echo "    systemctl --user stop suprema-bridge     # stop"
else
  echo "  To run in the background, use tmux/screen or your OS service manager."
fi
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Next: sign in at supremanode.com, pair this bridge (id: $BRIDGE_ID)"
echo "  Docs: https://github.com/supremanode/bridge#readme"
