#!/usr/bin/env bash
# Suprema Node — bridge installer.
#
# Usage:  curl -fsSL https://supremanode.com/install.sh | bash
#    or:  ./install.sh [--relay URL] [--branch main]
#
# What this does:
#   1. checks node + pnpm (or installs pnpm)
#   2. clones the repo (or updates if present)
#   3. installs deps
#   4. prompts for the relay URL (or uses --relay)
#   5. writes .env
#   6. installs a systemd user service (Linux) or prints the run command
#
# The bridge polls the relay for tasks and runs them via a detected harness
# (claude-code, codex, pi, etc.). It needs node; it does NOT need the relay's
# Postgres or any DB.
set -euo pipefail

BRIDGE_DIR="${BRIDGE_DIR:-$HOME/.suprema/bridge}"
REPO="${REPO:-https://github.com/jamezun/suprema-node.git}"
BRANCH="${BRANCH:-main}"
RELAY_URL=""

# ── arg parse ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --relay)   RELAY_URL="$2"; shift 2 ;;
    --branch)  BRANCH="$2"; shift 2 ;;
    --dir)     BRIDGE_DIR="$2"; shift 2 ;;
    -h|--help) echo "Usage: install.sh [--relay URL] [--branch main] [--dir PATH]"; exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

echo "╔════════════════════════════════════════════╗"
echo "║   Suprema Node — bridge installer          ║"
echo "╚════════════════════════════════════════════╝"
echo "  target: $BRIDGE_DIR"
echo ""

# ── 1. prerequisites ───────────────────────────────────────────────────────
if ! command -v node >/dev/null 2>&1; then
  echo "✗ node not found. Install Node 20+: https://nodejs.org"
  exit 1
fi
echo "✓ node $(node --version)"

if ! command -v pnpm >/dev/null 2>&1; then
  echo "  installing pnpm…"
  npm install -g pnpm >/dev/null 2>&1 || corepack enable pnpm >/dev/null 2>&1 || true
fi
command -v pnpm >/dev/null 2>&1 && echo "✓ pnpm $(pnpm --version)" || { echo "✗ pnpm install failed"; exit 1; }

# ── 2. clone or update ─────────────────────────────────────────────────────
if [[ -d "$BRIDGE_DIR/.git" ]]; then
  echo "  updating existing clone…"
  git -C "$BRIDGE_DIR" fetch --quiet origin
  git -C "$BRIDGE_DIR" checkout "$BRANCH" --quiet
  git -C "$BRIDGE_DIR" reset --hard "origin/$BRANCH" --quiet
else
  echo "  cloning repo…"
  mkdir -p "$(dirname "$BRIDGE_DIR")"
  git clone --depth 1 --branch "$BRANCH" "$REPO" "$BRIDGE_DIR" --quiet
fi
echo "✓ code at $BRIDGE_DIR"

# ── 3. install deps ────────────────────────────────────────────────────────
echo "  installing dependencies (this takes a minute)…"
( cd "$BRIDGE_DIR" && pnpm install --frozen-lockfile >/dev/null 2>&1 || pnpm install >/dev/null 2>&1 )
echo "✓ dependencies installed"

# ── 4. relay URL ───────────────────────────────────────────────────────────
if [[ -z "$RELAY_URL" ]]; then
  # default: this machine's Tailscale IP if present
  TS_IP="$(tailscale ip -4 2>/dev/null || true)"
  DEFAULT_RELAY="${TS_IP:+http://$TS_IP:4000}"
  read -r -p "Relay URL${DEFAULT_RELAY:+ [$DEFAULT_RELAY]}: " RELAY_URL
  RELAY_URL="${RELAY_URL:-$DEFAULT_RELAY}"
  if [[ -z "$RELAY_URL" ]]; then
    echo "✗ relay URL required (the machine running the relay, e.g. http://100.x.x.x:4000)"
    exit 1
  fi
fi

# ── 5. write .env ──────────────────────────────────────────────────────────
BRIDGE_ID="$(hostname)-$(date +%s | tail -c 5)"
cat > "$BRIDGE_DIR/apps/bridge/.env" <<EOF
# Suprema Node bridge — generated by install.sh
BRIDGE_ID=$BRIDGE_ID
RELAY_URL=$RELAY_URL
# poll interval (ms)
BRIDGE_POLL_MS=2000
EOF
echo "✓ configured for relay: $RELAY_URL (id: $BRIDGE_ID)"

# ── 6. start (systemd if Linux, else print cmd) ────────────────────────────
echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "  Install complete. Start the bridge with:"
echo ""
echo "    cd $BRIDGE_DIR"
echo "    pnpm --filter @suprema/bridge dev"
echo ""
echo "  (Add a harness so it can execute tasks: e.g. 'npm i -g @anthropic-ai/claude-code')"
if [[ "$(uname -s)" == "Linux" ]] && command -v systemctl >/dev/null 2>&1; then
  echo ""
  echo "  To run as a background service (Linux):"
  echo "    cd $BRIDGE_DIR && bash scripts/service.sh install"
fi
echo "╚═══════════════════════════════════════════════════════════════╝"
